# Generated by Django 4.0.2 on 2022-02-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории форумов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название форума')),
                ('description', models.CharField(default='', max_length=200, verbose_name='Краткое описание темы форума')),
                ('status', models.CharField(choices=[('opened', 'opened'), ('closed', 'closed'), ('hiddened', 'hiddened')], default='opened', max_length=10)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='app_forums.categories')),
            ],
            options={
                'verbose_name': 'Форум',
                'verbose_name_plural': 'Форумы',
                'db_table': 'forums',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок темы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('opened', 'opened'), ('closed', 'closed'), ('hiddened', 'hiddened')], default='opened', max_length=10)),
                ('type', models.CharField(choices=[('simple', 'simple'), ('important', 'important'), ('attention', 'attention')], default='simple', max_length=10)),
                ('counted_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forums', to='app_forums.forums')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topic_users', to='app_profile.users')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'db_table': 'topics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Заголовок сообщения')),
                ('message', models.TextField(default='', verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('editable', 'editable'), ('closed', 'closed'), ('hiddened', 'hiddened')], default='editable', max_length=10)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='app_forums.topics')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_users', to='app_profile.users')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
    ]
