# Generated by Django 4.0.2 on 2022-03-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0001_initial'),
        ('app_forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forums',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderators', to='app_profile.Users', verbose_name='Модераторы форума'),
        ),
    ]
