# Generated by Django 4.0.2 on 2022-03-03 15:59

import app_forums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forums', '0002_forums_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='title',
            field=models.CharField(max_length=100, validators=[app_forums.models.check_title_topic], verbose_name='Заголовок темы'),
        ),
    ]
