# Generated by Django 4.0.2 on 2022-03-03 16:02

import app_forums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forums', '0003_alter_topics_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, validators=[app_forums.models.check_title_topic], verbose_name='Заголовок сообщения'),
        ),
    ]
