# Generated by Django 4.0.2 on 2022-03-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forums', '0004_alter_messages_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='topic_start',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Первое сообщение темы'),
        ),
    ]
