# Generated by Django 4.0.2 on 2022-03-06 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_users_ninja'),
        ('app_forums', '0005_messages_topic_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_time', models.DateTimeField(auto_now_add=True, verbose_name='Время захода')),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stat_users', to='app_profile.users')),
            ],
            options={
                'verbose_name': 'Статистика пользователей на сайте',
                'verbose_name_plural': 'Статистика пользователей на сайте',
                'db_table': 'statusers',
                'ordering': ['-enter_time'],
            },
        ),
    ]
