# Generated by Django 4.0.2 on 2022-03-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forums', '0006_statusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusers',
            name='enter_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время захода'),
        ),
    ]
