# Generated by Django 4.0.2 on 2022-03-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_users_ninja'),
        ('app_forums', '0008_statusers_forum_statusers_topic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statusers',
            unique_together={('ip', 'user')},
        ),
    ]
