# Generated by Django 4.0.2 on 2022-03-11 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_forums', '0016_alter_topics_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последней записи'),
        ),
    ]
