# Generated by Django 4.0.2 on 2022-03-19 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0008_users_msgs_users_thanks'),
        ('app_forums', '0017_alter_messages_updated_at_alter_topics_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forums',
            name='sum_topics',
            field=models.IntegerField(default=0, verbose_name='Сумма тем форума'),
        ),
        migrations.AddField(
            model_name='topics',
            name='sum_msgs',
            field=models.IntegerField(default=0, verbose_name='Сумма сообщений темы'),
        ),
        migrations.AlterField(
            model_name='forums',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='forums', to='app_forums.categories'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msgs_this_topic', to='app_forums.topics'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='msgs_this_user', to='app_profile.users'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topics_this_forum', to='app_forums.forums'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topics_this_user', to='app_profile.users'),
        ),
    ]
