# Generated by Django 4.0.2 on 2022-03-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forums', '0018_forums_sum_topics_topics_sum_msgs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер сообщения в теме'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='sum_msgs',
            field=models.IntegerField(default=1, verbose_name='Сумма сообщений темы'),
        ),
    ]
