# Generated by Django 4.0.2 on 2022-03-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_forums', '0019_messages_number_alter_topics_sum_msgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='answer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_which_this_answer', to='app_forums.messages'),
        ),
    ]
