# Generated by Django 4.0.2 on 2022-03-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ninja',
            field=models.BooleanField(default=False, verbose_name='Скрытность пользователя'),
        ),
    ]
