# Generated by Django 4.0.2 on 2022-03-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0005_users_acknowledgements'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последней активности по StatUsers'),
        ),
    ]
