# Generated by Django 4.0.2 on 2022-03-12 14:32

import app_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0006_users_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='img/user.svg', upload_to=app_profile.models.user_directory_path),
        ),
    ]
